config/routes.rb
Rails.application.routes.draw do

  resources :app_preferences, except: [:show] do
    collection do
      get 'configure_prefs'
      post 'save_configured_prefs'
    end
  end
  resources :announcements, only: [ :index, :show, :edit, :update ]

  resources :resource_states, except: [:index, :show, :destroy]
  post '/resource_states/update_resource_states/:id', to: 'resource_states#update_resource_states', as: :update_resource_states
  
  resources :specific_attribute_states, except: [:index, :show, :destroy]
  post '/specific_attribute_states/update_specific_attribute_states/:id', to: 'specific_attribute_states#update_specific_attribute_states', as: :update_specific_attribute_states

  resources :common_attribute_states, except: [:index, :show, :destroy]
  post '/common_attribute_states/update_common_attribute_states/:id', to: 'common_attribute_states#update_common_attribute_states', as: :update_common_attribute_states

  resources :common_attributes, except: [:show]
  post 'unarchive_common_attribute/:id', to: 'common_attributes#unarchive', as: :unarchive_common_attribute
  resources :rovers, except: [:show]
  
  resources :zones, :except => [:show]
  resources :zones do
    resources :buildings, module: :zones
  end
  delete 'zones/buildings/:zone_id/:id', to: 'zones/buildings#remove_building', as: :remove_building

  resources :reports, only: [:index] do
    collection do
      get 'number_of_room_issues_report', to: 'reports#number_of_room_issues_report'
      get 'room_issues_report', to: 'reports#room_issues_report'
      get 'inspection_rate_report', to: 'reports#inspection_rate_report'
      get 'no_access_report', to: 'reports#no_access_report'
      get 'common_attribute_states_report', to: 'reports#common_attribute_states_report'
      get 'specific_attribute_states_report', to: 'reports#specific_attribute_states_report'
      get 'resource_states_report', to: 'reports#resource_states_report'
      get 'no_access_for_n_times_report', to: 'reports#no_access_for_n_times_report'
      get 'not_checked_rooms_report', to: 'reports#not_checked_rooms_report'
    end
  end

  get 'dashboard', to: 'static_pages#dashboard', as: :dashboard

  resources :rooms, :except => [:index, :edit, :update]
  resources :rooms do
    resources :specific_attributes, module: :rooms, except: [:show]
    resources :room_states, module: :rooms, except: [:destroy]
    resources :room_tickets, module: :rooms, only: [:send_email_for_tdx_ticket]
  end
  post 'archive_room/:id', to: 'rooms#archive', as: :archive_room
  post 'unarchive_room/:id', to: 'rooms#unarchive', as: :unarchive_room
  resources :notes, :except => [:index]
  post 'archive_specific_attribute/:room_id/:id', to: 'rooms/specific_attributes#archive', as: :archive_specific_attribute
  post 'unarchive_specific_attribute/:room_id/:id', to: 'rooms/specific_attributes#unarchive', as: :unarchive_specific_attribute

  resources :floors
  resources :buildings do
    resources :floors do 
      resources :rooms, module: :floors
    end
  end
  post 'archive_building/:id', to: 'buildings#archive', as: :archive_building
  post 'unarchive_building/:id', to: 'buildings#unarchive', as: :unarchive_building
  post 'unarchive_building_index/:id/:show_archived', to: 'buildings#unarchive_index', as: :unarchive_building_index

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions"} do
    delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resource :rover_navigation, only: [] do
    member do
      get 'zones'
      get 'buildings'
      get 'rooms'
      get 'confirmation'
    end
  end

  get 'redirect_to_unchecked_form/:id', to: 'rover_navigations#redirect_to_unchecked_form', as: :redirect_to_unchecked_form


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'static_pages#about', as: :all_root

  get 'static_pages/about'

  get 'welcome_rovers', to: 'static_pages#welcome_rovers', as: :welcome_rovers

  post '/send_email_for_tdx_ticket/:room_id', to: 'rooms/room_tickets#send_email_for_tdx_ticket', as: :send_email_for_tdx_ticket

  # LSA TDX Feedback routes
  mount LsaTdxFeedback::Engine => '/lsa_tdx_feedback', as: 'lsa_tdx_feedback'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?

  # Place this at the very end of the file to catch all undefined routes
  # get '*path', to: 'application#render_404', via: :all

end

app/views/shared/_footer.html.erb
<footer class="footer mx-5 mt-auto py-3 bg-white">
  <div class="d-flex flex-lg-row justify-content-between flex-column">
    <div class="center text-center">
      <p class="d-none d-md-block">
        <%= image_tag 'LSA_Technology_logo.svg', alt: 'LSA Technology Logo', class: "img-fluid" %>
      </p>
      <p class="text-center footer-bold d-md-none">
        LSA Technology Services
      </p><!-- Left column content for small viewports -->
    </div>
    <div>
      <p class="text-center mb-0 small">
        <a href="https://umich.edu/about/privacy/" class="footer-text footer-link" >Privacy Notice</a> |
        <button id="myCustomTrigger" class="hover:underline px-1 footer-text footer-link border-0 bg-transparent p-0" data-email="<%= session&.[](:user_email) %>">Report an Issue</button> |
        <span class="footer-text">734.615.0100</span>
      </p>
    </div>
    <div>
      <p class="d-none d-md-block text-center footer-text">
        ©<%= Time.now.year %>
        <a href="https://regents.umich.edu/" class="footer-text footer-link">|The Regents of the University of Michigan</a>
      </p>
      <p class="d-md-none text-center mb-0 footer-text">
        <a href="https://regents.umich.edu/" class="footer-text footer-link" >The Regents of the University of Michigan</a>
        <br>©<%= Time.now.year %>
      </p><!-- Right column content -->
    </div>
  </div>
  <script type="text/javascript" src="https://umlsait.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-T/1kwsvv/b/8/c95134bc67d3a521bb3f4331beb9b804/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=54564fa1"></script>
  <%= javascript_include_tag 'feedback', async: true %>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-um-blue">
  <div class="container-fluid" style="--bs-focus-ring-color:#E5E5E5;" >
    <%= link_to root_path, class: "a-nav focus-ring border-0 rounded-2" do %>
    <div id="LSAlogo" class="d-flex align-items-center">
      <div class="navbar-brand">
        <%= image_tag 'LSA_Logo.svg', alt: 'LSA Logo', class: 'logo_image' %>
      </div>
      <div class="nav-title h-100">
        SpaceReady
      </div>
    </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarBurgerMenu" aria-controls="navbarBurgerMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <!-- this is regular navbar-->
    <div class="collapse navbar-collapse d-none d-md-block">
      <% if user_signed_in? %>
      <% if is_admin? || is_readonly? %>
        <div class="nav-item dropdown navbar_dropdown_item h-100 px-2 rounded-0 border-0">
          <a class="nav-link h-100 d-flex align-items-center fs-5 focus-ring border-0 rounded-2" style="--bs-focus-ring-color:#E5E5E5;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Main
          </a>
          <ul class="dropdown-menu bg-primary rounded-0 navbar_dropdown_item">
            <li>
              <%= link_to "Dashboard", dashboard_path, class: 'dropdown-item navbar_dropdown_item' if policy(:static_page).dashboard? %>
            </li>
            <li>
              <%= link_to "Zones", zones_path, class: 'dropdown-item navbar_dropdown_item' if policy(Zone).index? %>
            </li>
            <li>
              <%= link_to "Buildings", buildings_path, class: 'dropdown-item navbar_dropdown_item' if policy(Building).index?%>
            </li>
          </ul>
        </div>
        <div class="nav-item dropdown navbar_dropdown_item h-100 px-2 rounded-0 border-0">
          <a class="nav-link h-100 d-flex align-items-center fs-5 focus-ring border-0 rounded-2" style="--bs-focus-ring-color:#E5E5E5;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Admin
          </a>
          <ul class="dropdown-menu bg-primary rounded-0 navbar_dropdown_item">
            <li>
              <%= link_to "Common Attributes", common_attributes_path, class: 'dropdown-item navbar_dropdown_item' if policy(CommonAttribute).index? %>
            </li>
            <li>
              <%= link_to "Create Preferences", app_preferences_path, class: 'dropdown-item navbar_dropdown_item' if policy(AppPreference).index? %>
            </li>
            <li>
              <%= link_to "App Preferences", configure_prefs_app_preferences_path, class: 'dropdown-item navbar_dropdown_item' if policy(AppPreference).configure_prefs? %>
            </li>
            <li>
              <%= link_to "Announcements", announcements_path, class: 'dropdown-item navbar_dropdown_item' if policy(Announcement).update? %>
            </li>
            <li>
              <%= link_to "Rovers", rovers_path, class: 'dropdown-item navbar_dropdown_item'if policy(Rover).index? %>
            </li>
            <li>
              <%= link_to "Reports", reports_path, class: 'dropdown-item navbar_dropdown_item'if policy(:report).index? %>
            </li>
            <li>
              <%= link_to "Docs", "https://docs.google.com/document/u/2/d/e/2PACX-1vTMubvxusmTGWEiRYq9EkYuC_0B_ylkCxFwA9uXlMZSjPW5r4KX20fcDCkRmIVgB3Ma5wA1Nm9CxNYO/pub", target: "_blank", class: 'dropdown-item navbar_dropdown_item' if policy(AppPreference).configure_prefs? %>
            </li>
          </ul>
        </div>
      <% end %>
      <% if is_rover? || is_admin? %>
      <div class="nav-item dropdown navbar_dropdown_item h-100 px-2 rounded-0 border-0" style="--bs-focus-ring-color:#E5E5E5;">
        <%= link_to "Rover Form", zones_rover_navigation_path, class: 'nav-link h-100 d-flex align-items-center fs-5 focus-ring border-0 rounded-2' if policy(:rover_navigation).zones? %>
      </div>
      <ul class="dropdown-menu bg-primary rounded-0 navbar_dropdown_item">
        <li>
          <%= link_to "Choose Room", zones_rover_navigation_path, class: 'dropdown-item navbar_dropdown_item' if policy(:rover_navigation).zones? %>
        </li>
      </ul>
    </div>
    <% end %>
    <% end %>
  </div>
  <!-- this is the hamburger menu-->
  <div class="collapse navbar-collapse d-md-none" id="navbarBurgerMenu">
    <% if user_signed_in? %>
      <div class="nav-section">
        <br />
        <div class="container d-flex justify-content-center">
          <div class="card p-4">
            <div class="d-flex flex-row justify-content-center align-items-center">
              <span class="idd1">
                <p class="h2-title"><%= current_user.display_name %></p>
              </span>
            </div>
            <div class="d-flex flex-row justify-content-center align-items-center"><span><%= current_user.principal_name %></span> </div>
            <div class="d-flex flex-row justify-content-center align-items-center mt-2">
              <%= button_to destroy_user_session_path, method: :delete, data: {turbo: "false"}, class: "btn btn-sign" do %>
                <span>Log Out</span>
              <% end %> 
            </div>
          </div>
        </div>
        <br />
        <% if is_admin? || is_readonly? %>
          <p style="font-weight: bold;">Main</p>
          <hr>
          <%= link_to "Dashboard", dashboard_path, class: 'dropdown-item navbar_dropdown_item' if policy(:static_page).dashboard? %>
          <%= link_to "Zones", zones_path, class: 'dropdown-item navbar_dropdown_item' if policy(Zone).index? %>
          <%= link_to "Buildings", buildings_path, class: 'dropdown-item navbar_dropdown_item' if policy(Building).index?%>
          <br>
          <p style="font-weight: bold;">Admin</p>
          <hr>
          <%= link_to "Common Attributes", common_attributes_path, class: 'dropdown-item navbar_dropdown_item' if policy(CommonAttribute).index? %>
          <%= link_to "Create Preferences", app_preferences_path, class: 'dropdown-item navbar_dropdown_item' if policy(AppPreference).index? %>
          <%= link_to "App Preferences", configure_prefs_app_preferences_path, class: 'dropdown-item navbar_dropdown_item' if policy(AppPreference).configure_prefs? %>
          <%= link_to "Announcements", announcements_path, class: 'dropdown-item navbar_dropdown_item' if policy(Announcement).update? %>
          <%= link_to "Rovers", rovers_path, class: 'dropdown-item navbar_dropdown_item'if policy(Rover).index? %>
          <%= link_to "Reports", reports_path, class: 'dropdown-item navbar_dropdown_item'if policy(:report).index? %>
          <%= link_to "Docs", "https://docs.google.com/document/u/2/d/e/2PACX-1vTMubvxusmTGWEiRYq9EkYuC_0B_ylkCxFwA9uXlMZSjPW5r4KX20fcDCkRmIVgB3Ma5wA1Nm9CxNYO/pub", target: "_blank", class: 'dropdown-item navbar_dropdown_item' if policy(AppPreference).configure_prefs? %>
        <% end %>
        <br>
        <% if is_rover? || is_admin? %>
          <%= link_to "Rover Form", zones_rover_navigation_path, class: 'dropdown-item navbar_dropdown_item font-weight: bold' if policy(:rover_navigation).zones? %>
          <hr>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="nav-item dropdown navbar_dropdown_item h-100 px-2 mr-2 rounded-0 border-0 hide-on-mobile">
      <a class="nav-link h-50 d-flex align-items-center focus-ring border-0 rounded-2 body-md-text p-2 mt-3 hide-on-mobile nav-user" style="--bs-focus-ring-color:#E5E5E5;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.display_name %>
      </a>
      <ul class="dropdown-menu bg-primary rounded-0 navbar_dropdown_item">
        <div class="container d-flex justify-content-center" style="position: absolute; top:0; right:0; width:400px;">
          <div class="card p-4">
            <div class="d-flex flex-row justify-content-center align-items-center">
              <span class="idd1">
                <p class="h2-title"><%= current_user.display_name %></p>
              </span>
            </div>
            <div class="d-flex flex-row justify-content-center align-items-center"><span><%= current_user.principal_name %></span> </div>
            <div class="d-flex flex-row justify-content-center align-items-center mt-2">
              <%= button_to destroy_user_session_path, method: :delete, data: {turbo: "false"}, class: "btn btn-sign " do %>
                Log Out
              <% end %> 
            </div>
          </div>
        </div>
      </ul>
    </div>
  <% end %>
</nav>

app/views/shared/_tdxtickets.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Email to Report Issues
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title fs-5" id="exampleModalLabel">Send an Issue Email</h2>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% if room_recent_tickets(@room).count > 0 %>
          
          <h3 class="fs-6">Recent Room Issues Reported</h3>
          <p>Please do not submit a new ticket if issue is listed below</p>
          <div class="mb-4">
            <table class="table table-sm table-dark">
              <% room_recent_tickets(@room).each do |ticket| %>
                <tr>
                  <th scope="col" class="ml-2">Date:</th>
                  <td>
                    <%= show_date_with_time(ticket.updated_at) %>
                  </td>
                </tr>
                <tr>
                  <th scope="col" class="ml-2">Message: </th>
                  <td>
                    <%= ticket.description %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
        <% end %>
        <div data-controller="room-tickets">
          <%= form_with(model: [@room, room_ticket = @room.room_tickets.new], url: send_email_for_tdx_ticket_path(@room), data: {room_tickets_target: "form", action: "room-tickets#check"}) do |form| %>
            <% if room_ticket.errors.any? %>
              <div class="text-danger">
              <p class="h3-title"><%= pluralize(room_ticket.errors.count, "error") %></p>
              <ul>
                <% room_ticket.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
              </div>
            <% end %>
            <div>
              <%= form.label :tdx_email, "Select the Email Address *" %>
              <%= form.select(:tdx_email, options_for_select(tdx_emails(@room.floor.building))) %>
            </div>
            <div>
              <div>Email Message *</div>
              <%= form.rich_text_area :description, data: { room_tickets_target: "description"} %>
            </div>
            <div class="mt-1 gap-1 d-flex flex-row justify-content-start align-items-center">
              <%= form.submit 'Submit', id: "submit_button", data: { action: "room-tickets#check", bs_dismiss: "modal" } %>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>