config/routes.rb
Rails.application.routes.draw do

  resources :app_preferences, except: [:show] do
    collection do
      get 'configure_prefs'
      post 'save_configured_prefs'
    end
  end
  resources :announcements, only: [ :index, :show, :edit, :update ]

  resources :resource_states, except: [:index, :show, :destroy]
  post '/resource_states/update_resource_states/:id', to: 'resource_states#update_resource_states', as: :update_resource_states
  
  resources :specific_attribute_states, except: [:index, :show, :destroy]
  post '/specific_attribute_states/update_specific_attribute_states/:id', to: 'specific_attribute_states#update_specific_attribute_states', as: :update_specific_attribute_states

  resources :common_attribute_states, except: [:index, :show, :destroy]
  post '/common_attribute_states/update_common_attribute_states/:id', to: 'common_attribute_states#update_common_attribute_states', as: :update_common_attribute_states

  resources :common_attributes, except: [:show]
  post 'unarchive_common_attribute/:id', to: 'common_attributes#unarchive', as: :unarchive_common_attribute
  resources :rovers, except: [:show]
  
  resources :zones, :except => [:show]
  resources :zones do
    resources :buildings, module: :zones
  end
  delete 'zones/buildings/:zone_id/:id', to: 'zones/buildings#remove_building', as: :remove_building

  resources :reports, only: [:index] do
    collection do
      get 'number_of_room_issues_report', to: 'reports#number_of_room_issues_report'
      get 'room_issues_report', to: 'reports#room_issues_report'
      get 'inspection_rate_report', to: 'reports#inspection_rate_report'
      get 'no_access_report', to: 'reports#no_access_report'
      get 'common_attribute_states_report', to: 'reports#common_attribute_states_report'
      get 'specific_attribute_states_report', to: 'reports#specific_attribute_states_report'
      get 'resource_states_report', to: 'reports#resource_states_report'
      get 'no_access_for_n_times_report', to: 'reports#no_access_for_n_times_report'
      get 'not_checked_rooms_report', to: 'reports#not_checked_rooms_report'
    end
  end

  get 'dashboard', to: 'static_pages#dashboard', as: :dashboard

  resources :rooms, :except => [:index, :edit, :update]
  resources :rooms do
    resources :specific_attributes, module: :rooms, except: [:show]
    resources :room_states, module: :rooms, except: [:destroy]
    resources :room_tickets, module: :rooms, only: [:send_email_for_tdx_ticket]
  end
  post 'archive_room/:id', to: 'rooms#archive', as: :archive_room
  post 'unarchive_room/:id', to: 'rooms#unarchive', as: :unarchive_room
  resources :notes, :except => [:index]
  post 'archive_specific_attribute/:room_id/:id', to: 'rooms/specific_attributes#archive', as: :archive_specific_attribute
  post 'unarchive_specific_attribute/:room_id/:id', to: 'rooms/specific_attributes#unarchive', as: :unarchive_specific_attribute

  resources :floors
  resources :buildings do
    resources :floors do 
      resources :rooms, module: :floors
    end
  end
  post 'archive_building/:id', to: 'buildings#archive', as: :archive_building
  post 'unarchive_building/:id', to: 'buildings#unarchive', as: :unarchive_building
  post 'unarchive_building_index/:id/:show_archived', to: 'buildings#unarchive_index', as: :unarchive_building_index

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions"} do
    delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resource :rover_navigation, only: [] do
    member do
      get 'zones'
      get 'buildings'
      get 'rooms'
      get 'confirmation'
    end
  end

  get 'redirect_to_unchecked_form/:id', to: 'rover_navigations#redirect_to_unchecked_form', as: :redirect_to_unchecked_form


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'static_pages#about', as: :all_root

  get 'static_pages/about'

  get 'welcome_rovers', to: 'static_pages#welcome_rovers', as: :welcome_rovers

  post '/send_email_for_tdx_ticket/:room_id', to: 'rooms/room_tickets#send_email_for_tdx_ticket', as: :send_email_for_tdx_ticket

  # LSA TDX Feedback routes
  mount LsaTdxFeedback::Engine => '/lsa_tdx_feedback', as: 'lsa_tdx_feedback'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?

  # Place this at the very end of the file to catch all undefined routes
  # get '*path', to: 'application#render_404', via: :all

end

app/models/building.rb
# == Schema Information
#
# Table name: buildings
#
#  id         :bigint           not null, primary key
#  bldrecnbr  :string
#  name       :string
#  nick_name  :string
#  address    :string
#  city       :string
#  state      :string
#  zip        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  zone_id    :bigint
#  archived   :boolean          default(FALSE)
#
class Building < ApplicationRecord
  has_many :floors
  belongs_to :zone, optional: true

  validates :bldrecnbr, uniqueness: true, presence: true
  validates :name, uniqueness: true

  scope :active, -> { where(archived: false).order(:name) }
  scope :archived, -> { where(archived: true).order(:name) }

  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end

  def active_rooms
    Room.active.joins(floor: [:building]).where(building: {id: self.id})
  end

  def rooms
    Room.joins(floor: [:building]).where(building: {id: self.id})
  end

  def has_checked_active_rooms?
    active_rooms.detect(&:room_state?).present?
  end

  def has_checked_rooms?
    rooms.detect(&:room_state?).present?
  end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :auth_user
  before_action :set_building, only: %i[ show edit update destroy archive unarchive unarchive_index] 
  before_action :set_zone
  include BuildingApi

  def index
    @zones = Zone.all.order(:name).map { |z| [z.name, z.id] }
    @zones << ["No Zone", 0]
    if params[:show_archived] == "1" 
      @buildings = Building.archived
      @archived = true
    else
      @buildings = Building.active
      @archived = false
    end

    if params[:zone_id].present?
      zone_id = params[:zone_id]
      if zone_id == "0"
        @buildings = Building.active.where(zone_id: nil)
      else
        @buildings = Building.active.where(zone_id: zone_id)
      end
    end
    
    if params[:search].present?
      search_term = "%#{params[:search]}%"
      @buildings = @buildings.where('name ILIKE ? OR address ILIKE ? OR bldrecnbr ILIKE ? OR nick_name ILIKE ?', search_term, search_term, search_term, search_term)
    end

    @buildings = @buildings
    authorize @buildings
  end

  def new
    @building = Building.new
    @zones = Zone.all
    authorize @building
  end

  def create
    if building_params[:bldrecnbr].present?
      return add_from_bldrecnbr
    end
  end

  def show
    # to show/hide 'Show Archived Rooms' checkbox and show active or archived rooms on floors on Buiding show page
    @archived = params["show_archived_rooms"] == "1" ? true : false 
    floors = @building.floors
    floor_names_sorted = sort_floors(floors.pluck(:name).uniq)
    @floors = floors.in_order_of(:name, floor_names_sorted)
  end

  def edit
    @zones = Zone.all.map { |z| [z.name, z.id] }
  end
    
  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    if @building.update(building_params)
        redirect_to building_path(@building), notice: notice
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @building.has_checked_rooms?
      flash.now['alert'] = "The buildings has checked rooms - archive this building instead"
      @buildings = Building.active
    else
      if delete_building(@building)
        redirect_to buildings_path, notice: "The building was deleted."
      else
        @buildings = Building.active
        flash.now["alert"] = "Error deleting building."
      end
    end
  end

  def archive
    session[:return_to] = request.referer
    if @building.zone.present?
      @building.update(zone_id: nil)
    end
    if change_building_archived_mode(building: @building, archived: true)
      @buildings = Building.active
      redirect_back_or_default(notice: "The building was archived")
    else
      @buildings = Building.active
    end
  end

  def unarchive
    session[:return_to] = request.referer
    @archived = true
    if change_building_archived_mode(building: @building, archived: false)
      @buildings = Building.archived
      redirect_back_or_default(notice: "The building was unarchived")
    else
      @buildings = Building.archived
    end
  end

  def unarchive_index
    session[:return_to] = request.referer
    authorize @building
    @archived = true
    if change_building_archived_mode(building: @building, archived: false)
      @buildings = Building.archived
      @zones = Zone.all.order(:name).map { |z| [z.name, z.id] }
      @zones << ["No Zone", 0]
      render :index, notice: "The building was unarchived"
    else
      @buildings = Building.archived
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:bldrecnbr, :name, :nick_name, :address, :city, :state, :zip, :zone_id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
      authorize @building
    end

    def set_zone
      # params[:zone_id] == 0 for "No Zones" option
      if params[:zone_id].present? && params[:zone_id] != "0"
        @zone_id = params[:zone_id]
        @zone = Zone.find(params[:zone_id])
      end
    end

    def add_from_bldrecnbr
      note = ""
      bldrecnbr = building_params[:bldrecnbr]
      @building = Building.new
      authorize @building
      result = get_building_info_by_bldrecnbr(bldrecnbr)
      if result['success']
        if result['data'].present?
          if result['data'].count > 1
            flash.now[:alert] = "The API returned multiple buildings for the #{bldrecnbr} number. Please change it."
            render :new, status: :unprocessable_entity
          else
            data = result['data'].first
            @building.zone_id = params[:zone_id]
            @building.bldrecnbr = data['BuildingRecordNumber']
            @building.name = data['BuildingLongDescription'].titleize
            address = "#{data['BuildingStreetNumber']}  #{data['BuildingStreetDirection']}  #{data['BuildingStreetName']}".strip.gsub(/\s+/, " ")
            @building.address = address.titleize
            @building.city = data['BuildingCity'].titleize
            @building.state = data['BuildingState']
            @building.zip = data['BuildingPostal']
            authorize @building
            respond_to do |format|
              if @building.save
                add_classrooms_for_building(bldrecnbr)
                notice = "New Building was added." + note
                @buildings = Building.active.where(zone: @zone)
                format.turbo_stream do
                  @new_building = Building.new
                  if @zone.present?
                  redirect_to zone_buildings_path(@zone), notice: notice
                  else 
                    redirect_to buildings_path, notice: notice
                  end
                end
              else
                format.html { render :new, status: :unprocessable_entity }
              end
            end
          end
        end
      else
        flash.now[:alert] = result['errorcode'] + result['error']
        render :new, status: :unprocessable_entity
      end
    end

    def add_classrooms_for_building(bldrecnbr)
      result = get_classrooms_for_building(bldrecnbr)
      if result['data'].present?
        rooms_data = result['data']
        rooms_data.each do |row|
          if row['RoomTypeDescription'] == "Classroom"
            if Floor.find_by(name: row["FloorNumber"], building: @building).present?
              floor = Floor.find_by(name: row["FloorNumber"], building: @building)
            else
             floor = Floor.new(name: row["FloorNumber"], building: @building)
             floor.save
            end
            room = Room.new(rmrecnbr: row["RoomRecordNumber"], room_number: row["RoomNumber"], room_type: "Classroom", floor: floor)
            room.save
          end
        end
      else
        note = " API returned bo data about classrooms for the building"
      end
    end

    def change_building_archived_mode(building:, archived:)
      ActiveRecord::Base.transaction do
        raise ActiveRecord::Rollback unless building.update(archived: archived)
        raise ActiveRecord::Rollback unless Room.where(floor_id: building.floors.ids).update_all(archived: archived)
        rooms = archived ? Room.archived.where(floor_id: building.floors.ids) : Room.active.where(floor_id: building.floors.ids)
        rooms.each do |room|
          raise ActiveRecord::Rollback unless room.specific_attributes.update(archived: archived)
          raise ActiveRecord::Rollback unless room.resources.update(archived: archived)
        end
      end
      true
    end

    def delete_building(building)
      begin
        rooms_ids = building.rooms.ids
        Resource.where(room_id: rooms_ids).delete_all
        SpecificAttribute.where(room_id: rooms_ids).delete_all
        Room.where(floor_id: building.floors.ids).delete_all
        Floor.where(building_id: building).delete_all
        if building.delete 
          return true
        else
          return false
        end
      rescue StandardError => e
        raise ActiveRecord::Rollback
        return false
      end
    end
end

app/controllers/zones/buildings_controller.rb
class Zones::BuildingsController < ApplicationController
  before_action :auth_user
  before_action :set_building, only: %i[ remove_building ]
  before_action :set_zone
  include BuildingApi

  def index
    @building = Building.new
    @buildings = Building.active.where(zone: @zone)
    authorize @buildings
  end

  def create
    if params[:building_id].present?
      return add_building_from_existing
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def remove_building
    authorize([@zone, @building])
    if @zone.buildings.delete(@building)
      @buildings = Building.active.where(zone: @zone)
      flash.now[:notice] = "The building was removed from the zone."
    end
    @building = Building.new
  end

  private
    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:bldrecnbr, :name, :nick_name, :address, :city, :state, :zip, :zone_id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    def set_zone
      @zone_id = params[:zone_id]
      @zone = Zone.find(params[:zone_id])
    end

    def add_building_from_existing
      @building = Building.find(params[:building_id])
      authorize([@zone, @building]) 
      if @zone.buildings << @building
        @building = Building.new
        @buildings = Building.active.where(zone: @zone)
        flash.now[:notice] = "The building was added."
      end
    end

end

app/views/buildings/_building.html.erb
<div id="<%= dom_id building %>">

  <p>
    <strong>Building Record Number:</strong>
    <%= building.bldrecnbr %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= building.name %>
  </p>

  <p>
    <strong>Nickname:</strong>
    <%= building.nick_name %>
  </p>
  
  <p>
    <strong>Address:</strong>
    <%= "#{building.address}, #{building.city}, #{building.state} #{building.zip}"%>
  </p>
  
  <p>
    <strong>Zone:</strong>
    <%= show_zone(building) %>
  </p>

</div>

<div>
  <% unless building.has_checked_rooms? %>
    <%= link_to building_path(building), class: "link_to", data: { turbo_confirm: "Are you sure you want to delete this building?", turbo_method: :delete } do %>
      Delete Building <i class="bi bi-trash-fill text-danger"></i>
    <% end %>
  <% else %>
    <% if building.archived %>
      <%= link_to unarchive_building_path(building), class: "link_to", data: { turbo_confirm: "Are you sure you want to unarchive this building?", turbo_method: :post }  do %>
        Unarchive Building <i class="bi bi-archive text-success"></i>
      <% end %>
      <% else %>
      <%= link_to archive_building_path(building), class: "link_to", data: { turbo_confirm: "Are you sure you want to archive this building?", turbo_method: :post }  do %>
        Archive Building <i class="bi bi-archive-fill text-success"></i>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/buildings/_edit_form.html.erb
<div id="<%= dom_id building %>">

  <p>
    <strong>Building Record Number:</strong>
    <%= building.bldrecnbr %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= building.name %>
  </p>
  
  <p>
    <strong>Address:</strong>
    <%= "#{building.address}, #{building.city}, #{building.state} #{building.zip}"%>
  </p>

<%= form_with model: [building], data: { controller: "building" } do |form| %>
  <% if building.errors.any? %>
    <div class="text-danger">
      <h2><%= pluralize(building.errors.count, "error") %></h2>

      <ul>
        <% building.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nick_name, 'Nickname', class: "nowrap" %>
    <%= form.text_field :nick_name, data: { building_target: "nickName" } %>
  </div>

  <div>
    <%= form.label :zone_id, class: "nowrap" %>
    <%= form.select(:zone_id, options_for_select(@zones, building.zone ? building.zone.id : nil ), { include_blank: "Select ..." } ) %>
  </div>

  <% if @zone.present? %>
    <%= hidden_field_tag :zone_id, @zone.id %>
  <% end %>


  <div class="d-flex flex-row justify-content-start align-items-center gap-3">
    <%= form.submit "Update", class: "btn btn-primary" %>
    <%= link_to "Cancel", :back, class: "link_to" %>
  </div>
<% end %>

app/views/buildings/_floors.html.erb
<%= turbo_frame_tag 'all_floors' do %>  
  <div class="accordion accordion-flush" id="buildingFloors">
    <% @floors.each do |floor| %>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed bg-accordion" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%= floor.id %>" aria-expanded="false" aria-controls="collapse_<%= floor.id %>">
            Floor <%= floor.name %> 
          </button>
        </h2>
        
        <div id="collapse_<%= floor.id %>" class="accordion-collapse collapse" data-bs-parent="#buildingFloors">
          <div class="accordion-body">
            <%= turbo_frame_tag 'all_rooms' do %>  
              <table class="table text-center">
                <thead class="table-group-divider">
                  <tr>
                    <th>Number</th>
                    <th>Room Type</th>
                    <th>Room Record Number</th>
                    <td>View</td>
                  </tr>
                </thead>
                <tbody class="table-group-divider">
                  <% if @archived %>
                    <% rooms = floor.archived_rooms %>
                  <% else %>
                    <% rooms = floor.active_rooms %>
                  <% end %>
                  <% rooms.order(:room_number).each do |room| %>
                    <tr class="building_tbody_tr">
                      <td class="building_tbody_td">
                        <%= link_to room.room_number, room_path(room), data: { turbo_frame: "_top" }, class: "link_to" %>
                      </td>
                      <td class="building_tbody_td">
                        <%= room.room_type %>
                      </td>
                      <td class="building_tbody_td">
                        <%= room.rmrecnbr %>
                      </td>
                      <td class="building_tbody_td">
                        <%= link_to room_path(room), class: "link_to", 'data-bs-toggle': "tooltip", 'data-bs-placement': "bottom", 'title': "View", data: { turbo_frame: "_top" } do %>
                        <i class="bi bi-eye-fill text-primary"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/buildings/_form.html.erb
<%= form_with model: building do |form| %>
  <% if building.errors.any? %>
    <div class="text-danger">
      <h2><%= pluralize(building.errors.count, "error") %></h2>
      <ul>
        <% building.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :bldrecnbr, 'Building Record Number', class: "nowrap" %>
    <%= form.text_field :bldrecnbr, required: true, placeholder: "Building Record Number" %>
  </div>

  <% if @zone.present? %>
    <%= form.hidden_field :zone_id, value: @zone.id %>
  <% end %>

  <div class="d-flex flex-row justify-content-start align-items-center gap-3">
    <%= form.submit %>
    <% if @zone.present? %>
      <%= link_to "Cancel", zone_buildings_path(@zone.id), class: "link_to" %>
    <% else %>
      <%= link_to "Cancel", buildings_path, class: "link_to" %>
    <% end %>
  </div>
<% end %>

app/views/buildings/_listing.html.erb
<%= turbo_frame_tag 'all_buildings' do %>  
  <table class="table text-center">
    <thead class="table-group-divider">
      <tr>
        <th class="text-start">Name</th>
        <th>Nickname</th>
        <th>Address</th>
        <th>Building Record Number</th>
        <th>Zone</th>
        <th>View</th>
        <th>Edit</th>
        <% if @archived %>
          <th>Unarchive</th>
        <% end %>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <% @buildings.each do |building| %>
        <tr class="building_tbody_tr">
          <td class="building_tbody_td text-start">
            <%= link_to building_path(building), data: { turbo_frame: "_top" }, class: "link_to" do%>
              <%= building.name %>
            <% end %>
          </td>
          <td class="building_tbody_td">
            <%= building.nick_name %>
          </td>
          <td class="building_tbody_td">
            <%= building.full_address %>
          </td>
          <td class="building_tbody_td">
            <%= building.bldrecnbr %>
          </td>
          </td>
          <td class="building_tbody_td">
            <%= show_zone(building) %>
          </td>
          <td class="building_tbody_td">
            <%= link_to building_path(building), 'data-bs-toggle': "tooltip", 'data-bs-placement': "bottom", 'title': "View", data: { turbo_frame: "_top" } do%>
            <i class="bi bi-eye-fill text-primary"></i>
            <% end %>
          </td>
          <td class="building_tbody_td">
            <%= link_to edit_building_path(building), 'data-bs-toggle': "tooltip", 'data-bs-placement': "bottom", 'title': "Edit", data: { turbo_frame: "_top" } do %>
            <i class="bi bi-pencil-square text-primary"></i>
            <% end %>
          </td>
          <% if @archived %>
             <td class="building_tbody_td">
              <%= link_to unarchive_building_index_path(building, "1"), 'data-bs-toggle': "tooltip", 'data-bs-placement': "bottom", 'title': "Unarchive", data: { turbo_confirm: "Are you sure you want to unarchive this building?" , turbo_method: :post }  do %>
                <i class="bi bi-archive text-success"></i>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/buildings/archive.turbo_stream.erb
<%= turbo_stream.update "all_buildings" do %>
    <%= render "listing" %>
<% end %>

<%= render_flash_stream %>

app/views/buildings/destroy.turbo_stream.erb
<%= turbo_stream.update "all_buildings" do %>
    <%= render "listing" %>
<% end %>

<%= render_flash_stream %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>
<%= render "edit_form", building: @building %>

app/views/buildings/index.html.erb
<div class="container-fluid" id="buildings">
  <div class="d-flex justify-content-between">
    <h1>Buildings</h1>
    <div class="mb-auto mt-auto">
      <%= link_to "Add New Building", new_building_path, class: "btn btn-primary" %>
    </div>
  </div>
  <div>
    <%= form_with url: buildings_path, method: :get, class: "", 
      data: { 
        controller: "autosubmit", 
        autosubmit_target: "form", 
        turbo_frame: "all_buildings" 
      } do |form| %>
      <div class="">
      <label for="search" aria-label="search" style="display: inline;"></label>
        <%= form.text_field :search, placeholder: "Search by Name, Nickname, Address, or Record Number", value: @search_query, data: { action: "input->autosubmit#search" } %>
      </div>
      <div class="">
        <label for="zone_id" aria-label="zone_id" style="display: inline;"></label>
        <%= form.select "zone_id", options_for_select(@zones, selected: params[:zone_id]), {include_blank: "Select Zone ..."}, { :"data-action" => "change->autosubmit#submitForm" } %>
      </div>
      <% if Building.archived.present? %>
        <div class="mt-2">
          <%= form.check_box :show_archived, class: "form-check-input", data: { action: "input->autosubmit#search" }  %>
          <%= form.label :show_archived, "Show Archived Buildings" %>
        </div>
      <% end %>
      <div class="mt-2">
        <a class="link_to" data-action="autosubmit#clearFilters">
          Clear Filters
        </a>
      </div>
    <% end %>
    <h3>
      <%= @zone.name if @zone.present?  %> Buildings (<%= @buildings.count %>)
    </h3>
    <%= render "listing" %>
  </div>
</div>

app/views/buildings/new.html.erb
<h1>Add New Building</h1>
<% if @zone.present? %>
  <h2><%= "to #{@zone.name}" %></h2>
<% end %>

<%= render "form", building: @building %>
<br>

app/views/buildings/show.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Building Details</h1>
  <div class="d-flex align-items-end flex-column gap-1 mt-2">
    <% if @zone.present? %>
      <%= link_to "Back to Buildings", zone_buildings_path(@zone), class: "link_to" %>
    <% else %>
      <%= link_to "Back to Buildings", buildings_path, class: "link_to" %>
    <% end %>
    <%= link_to "Edit Building", edit_building_path(@building), class: "btn btn-primary h-50 mt-auto mb-auto" %>
  </div>
</div>
<%= render @building %>

<% unless @building.archived %>
  <% if has_archived_rooms?(@building) %>
    <%= form_with url: building_path(@building), method: :get, class: "", 
          data: { 
            controller: "autosubmit", 
            autosubmit_target: "form", 
            turbo_frame: "all_floors" 
          } do |form| %>

      <div class="mt-2">
        <%= form.check_box :show_archived_rooms, class: "form-check-input", data: { action: "input->autosubmit#search" }  %>
        <%= form.label :show_archived_rooms, "Show Archived Rooms" %>
      </div>
    <% end %>
  <% end %>


  <div class="d-flex flex-row justify-content-start align-items-center gap-3">
    <h2>Rooms </h2>
    <%= link_to "Add Room", new_room_path(:building_id => @building.id), class: "mt-3 link_to" %>
  </div>

  <%= render 'floors' %>
<% end %>

app/views/buildings/unarchive.turbo_stream.erb
<%= turbo_stream.update "all_buildings" do %>
    <%= render "listing" %>
<% end %>

<%= render_flash_stream %>