config/routes.rb
Rails.application.routes.draw do

  resources :app_preferences, except: [:show] do
    collection do
      get 'configure_prefs'
      post 'save_configured_prefs'
    end
  end
  resources :announcements, only: [ :index, :show, :edit, :update ]

  resources :resource_states, except: [:index, :show, :destroy]
  post '/resource_states/update_resource_states/:id', to: 'resource_states#update_resource_states', as: :update_resource_states
  
  resources :specific_attribute_states, except: [:index, :show, :destroy]
  post '/specific_attribute_states/update_specific_attribute_states/:id', to: 'specific_attribute_states#update_specific_attribute_states', as: :update_specific_attribute_states

  resources :common_attribute_states, except: [:index, :show, :destroy]
  post '/common_attribute_states/update_common_attribute_states/:id', to: 'common_attribute_states#update_common_attribute_states', as: :update_common_attribute_states

  resources :common_attributes, except: [:show]
  post 'unarchive_common_attribute/:id', to: 'common_attributes#unarchive', as: :unarchive_common_attribute
  resources :rovers, except: [:show]
  
  resources :zones, :except => [:show]
  resources :zones do
    resources :buildings, module: :zones
  end
  delete 'zones/buildings/:zone_id/:id', to: 'zones/buildings#remove_building', as: :remove_building

  resources :reports, only: [:index] do
    collection do
      get 'number_of_room_issues_report', to: 'reports#number_of_room_issues_report'
      get 'room_issues_report', to: 'reports#room_issues_report'
      get 'inspection_rate_report', to: 'reports#inspection_rate_report'
      get 'no_access_report', to: 'reports#no_access_report'
      get 'common_attribute_states_report', to: 'reports#common_attribute_states_report'
      get 'specific_attribute_states_report', to: 'reports#specific_attribute_states_report'
      get 'resource_states_report', to: 'reports#resource_states_report'
      get 'no_access_for_n_times_report', to: 'reports#no_access_for_n_times_report'
      get 'not_checked_rooms_report', to: 'reports#not_checked_rooms_report'
    end
  end

  get 'dashboard', to: 'static_pages#dashboard', as: :dashboard

  resources :rooms, :except => [:index, :edit, :update]
  resources :rooms do
    resources :specific_attributes, module: :rooms, except: [:show]
    resources :room_states, module: :rooms, except: [:destroy]
    resources :room_tickets, module: :rooms, only: [:send_email_for_tdx_ticket]
  end
  post 'archive_room/:id', to: 'rooms#archive', as: :archive_room
  post 'unarchive_room/:id', to: 'rooms#unarchive', as: :unarchive_room
  resources :notes, :except => [:index]
  post 'archive_specific_attribute/:room_id/:id', to: 'rooms/specific_attributes#archive', as: :archive_specific_attribute
  post 'unarchive_specific_attribute/:room_id/:id', to: 'rooms/specific_attributes#unarchive', as: :unarchive_specific_attribute

  resources :floors
  resources :buildings do
    resources :floors do 
      resources :rooms, module: :floors
    end
  end
  post 'archive_building/:id', to: 'buildings#archive', as: :archive_building
  post 'unarchive_building/:id', to: 'buildings#unarchive', as: :unarchive_building
  post 'unarchive_building_index/:id/:show_archived', to: 'buildings#unarchive_index', as: :unarchive_building_index

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions"} do
    delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resource :rover_navigation, only: [] do
    member do
      get 'zones'
      get 'buildings'
      get 'rooms'
      get 'confirmation'
    end
  end

  get 'redirect_to_unchecked_form/:id', to: 'rover_navigations#redirect_to_unchecked_form', as: :redirect_to_unchecked_form


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'static_pages#about', as: :all_root

  get 'static_pages/about'

  get 'welcome_rovers', to: 'static_pages#welcome_rovers', as: :welcome_rovers

  post '/send_email_for_tdx_ticket/:room_id', to: 'rooms/room_tickets#send_email_for_tdx_ticket', as: :send_email_for_tdx_ticket

  # LSA TDX Feedback routes
  mount LsaTdxFeedback::Engine => '/lsa_tdx_feedback', as: 'lsa_tdx_feedback'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?

  # Place this at the very end of the file to catch all undefined routes
  # get '*path', to: 'application#render_404', via: :all

end

app/controllers/rooms/room_states_controller.rb
class Rooms::RoomStatesController < ApplicationController
  before_action :auth_user
  before_action :set_room
  before_action :set_room_state, only: %i[ show edit update ]
  before_action :set_notes_andannouncements, only: %i[new edit create]

  # GET /room_states or /room_states.json
  def index
    @room_states = room_states_by_period
    authorize @room_states
  end

  # GET /room_states/1 or /room_states/1.json
  def show
  end

  # GET /room_states/new
  def new
    @room_state = RoomState.new
    authorize @room_state
  end

  # GET /room_states/1/edit
  def edit
    authorize @room_state
  end

  # POST /room_states or /room_states.json
  def create
    @room_state = @room.room_states.new(room_state_params)
    authorize @room_state
    respond_to do |format|
      if @room_state.save
        unless @room.update(last_time_checked: DateTime.now)
          flash.now['alert'] = "Error updating room record"
          return
        end

        if @room_state.is_accessed?
          format.html { redirect_to redirect_rover_to_correct_state(room: @room, room_state: @room_state, step: "room", mode: "new") }
          format.json { render json: { status: 'ok' }, status: :ok }
        else
          format.html { redirect_to confirmation_rover_navigation_path(room_id: @room.id), notice: 'Room was successfully checked!' }
          format.json { render json: { status: 'ok' }, status: :ok }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { errors: @room_state.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_states/1 or /room_states/1.json
  def update
    respond_to do |format|
      if @room_state.update(room_state_params)
        unless @room.update(last_time_checked: DateTime.now)
          flash.now['alert'] = "Error updating room record"
          return
        end
        if @room_state.is_accessed?
          format.html { redirect_to redirect_rover_to_correct_state(room: @room, room_state: @room_state, step: "room", mode: "edit") }
        else
          format.html { redirect_to confirmation_rover_navigation_path(room_id: @room.id), notice: 'Room was successfully checked!' }
          format.json { render json: { status: 'ok' }, status: :ok }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_room
      @room = Room.find(params[:room_id])
      if AppPreference.find_by(name: 'no_access_reason').value.present?
        @no_access_reasons = AppPreference.find_by(name: 'no_access_reason')&.value&.split(',').map(&:strip)
      else
        @no_access_reasons = []
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_room_state
      @room_state = RoomState.find(params[:id])
      authorize @room_state
    end

    def set_notes_andannouncements
      @rovers_form_announcement = Announcement.find_by(location: "rovers_form")
      @notes = @room.notes.order("created_at DESC")
    end

    # Only allow a list of trusted parameters through.
    def room_state_params
      params.require(:room_state).permit(:checked_by, :is_accessed, :report_to_supervisor, :no_access_reason, :room_id)
    end

    def room_states_by_period
      start_time = params[:from].present? ? Date.parse(params[:from]).beginning_of_day : Date.new(0)
      end_time = params[:to].present? ? Date.parse(params[:to]).end_of_day : Date.today.end_of_day
      @room_states = RoomState.where(room_id: @room.id)
                          .where(created_at: start_time..end_time)
                          .order(updated_at: :desc)
                          .page(params[:page])
                          .per(5)
      return @room_states
    end
end

app/controllers/rooms/room_tickets_controller.rb
class Rooms::RoomTicketsController < ApplicationController
  before_action :auth_user
  before_action :set_room, only: %i[ send_email_for_tdx_ticket ]

  def send_email_for_tdx_ticket
    message = room_ticket_params[:description]
    tdx_email = room_ticket_params[:tdx_email]

    if tdx_emails(@room.floor.building).none? { |_, email| email == tdx_email }
      render json: { errors: ['Invalid email address.'] }, status: :unprocessable_entity and return
    end

    @room_ticket = RoomTicket.new(description: message, room_id: @room.id, submitted_by: current_user.uniqname, tdx_email: tdx_email )
    authorize @room_ticket

    respond_to do |format|
      if @room_ticket.save
        RoomTicketMailer.with(date: @room_ticket.created_at.strftime('%m/%d/%Y'), room: @room, message: message, submitter: current_user, tdx_email: tdx_email).send_tdx_ticket.deliver_now
        format.json { render json: { notice: "Room ticket was successfully sent." }, status: :ok }
      else
        format.json { render json: { errors: @room_ticket.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_ticket
      @room_ticket = RoomTicket.find(params[:id])
    end

    def set_room
      @room = Room.find(params[:room_id])
      @building = @room.floor.building
    end

    def room_ticket_params
      params.require(:room_ticket).permit(:description, :tdx_email)
    end
end

app/controllers/rooms/specific_attributes_controller.rb
class Rooms::SpecificAttributesController < ApplicationController
  before_action :auth_user
  before_action :set_room
  before_action :set_specific_attribute, only: %i[edit update destroy archive unarchive ]

  # GET /specific_attributes or /specific_attributes.json
  def index
    if params["show_archived"] == "1"
      @specific_attributes = SpecificAttribute.archived.where(room_id: @room)
      @action_title = "Unarchive"
    else
      @specific_attributes = SpecificAttribute.active.where(room_id: @room)
      @action_title = "Delete/Archive"
    end
    @archived = SpecificAttribute.archived.where(room_id: @room).present? ? true : false
  
    @new_specific_attribute = SpecificAttribute.new
    authorize @specific_attributes
  end

  # GET /specific_attributes/new
  def new
    @specific_attribute = SpecificAttribute.new
    authorize @specific_attribute
  end

  # GET /specific_attributes/1/edit
  def edit
  end

  # POST /specific_attributes or /specific_attributes.json
  def create
    @specific_attribute = @room.specific_attributes.new(specific_attribute_params)
    authorize @specific_attribute

    respond_to do |format|
      if @specific_attribute.save
        notice = "Specific attribute was successfully created."
        format.turbo_stream do
          @new_specific_attribute = SpecificAttribute.new
          flash.now[:notice] = notice
        end
        format.html { redirect_to room_specific_attributes_path(@room), notice: notice }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specific_attributes/1 or /specific_attributes/1.json
  def update
    respond_to do |format|
      if @specific_attribute.update(specific_attribute_params)
        format.html { redirect_to room_specific_attributes_path(@room), notice: "Specific attribute was successfully updated." }
        format.json { render :show, status: :ok, location: @specific_attribute }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @specific_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specific_attributes/1 or /specific_attributes/1.json
  def archive
    if @specific_attribute.update(archived: true)
      @room = Room.find(params[:room_id])
      @specific_attributes = SpecificAttribute.active.where(room_id: @room)
      @new_specific_attribute = SpecificAttribute.new
      @archived = true
      @action_title = "Delete/Archive"
      flash.now["notice"] = "The specific attribute was archived."
    else
      render :index, status: :unprocessable_entity 
    end
  end

  def unarchive
    if @specific_attribute.update(archived: false)
      @room = Room.find(params[:room_id])
      @specific_attributes = SpecificAttribute.archived.where(room_id: @room)
      @action_title = "Unarchive"
      flash.now["notice"] = "The specific attribute was unarchived."
    else
      render :index, status: :unprocessable_entity 
    end
  end

  def destroy
    @specific_attribute.destroy!
    @room = Room.find(params[:room_id])
    @specific_attributes = SpecificAttribute.active.where(room_id: @room)
    @action_title = "Delete/Archive"
    flash.now["notice"] = "Specific attribute was deleted."
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end
    # Use callbacks to share specific setup or constraints between actions.
  def set_specific_attribute
    @specific_attribute = SpecificAttribute.find(params[:id])
    authorize @specific_attribute
  end

  # Only allow a list of trusted parameters through.
  def specific_attribute_params
    params.require(:specific_attribute).permit(:description, :need_checkbox, :need_quantity_box, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :auth_user
  before_action :set_room, only: %i[ show destroy archive unarchive ]
  include BuildingApi

  # GET /rooms/1 or /rooms/1.json
  def show
    @common_attributes = CommonAttribute.active
    @new_note = Note.new(room: @room)
    @notes = @room.notes.order("created_at DESC")
  end

  # GET /rooms/new
  def new
    @room = Room.new
    @building = Building.find(params[:building_id])
    authorize @room
  end

  # POST /rooms or /rooms.json
  def create
    @building = Building.find(params[:building_id])
    rmrecnbr = room_params[:rmrecnbr]
    @room = Room.new(rmrecnbr: rmrecnbr)
    authorize @room
    bldrecnbr = @building.bldrecnbr
    result = get_room_info_by_rmrecnbr(bldrecnbr, rmrecnbr)
    if result['success']
      room_data = result['data']
      if Floor.find_by(name: room_data["FloorNumber"], building: @building).present?
        @floor = Floor.find_by(name: room_data["FloorNumber"], building: @building)
      else
       @floor = Floor.new(name: room_data["FloorNumber"], building: @building)
       @floor.save
      end
      @room = Room.new(rmrecnbr: room_data["RoomRecordNumber"], room_number: room_data["RoomNumber"], room_type: room_data["RoomTypeDescription"], floor: @floor)
      authorize @room
      if @room.save
        redirect_to building_path(@building), notice: "Room was successfully added to " + @floor.name + " floor."
      else
        render :new, status: :unprocessable_entity
      end
    else
      flash.now[:alert] = result['error']
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    if @room.room_states.present?
      flash.now['alert'] = "The rooms has checked states - archive this room instead"
      @rooms = Room.active
    else
      @building = @room.floor.building
      if delete_room(@room)
        redirect_to building_path(@building), notice: "The room was deleted."
      else
        flash.now['alert'] = "error deleting room"
      end
    end
  end

  def archive
    session[:return_to] = request.referer
    if change_room_archived_mode(room: @room, archived: true)
      redirect_back_or_default(notice: "The room was archived")
    else
      @rooms = Room.active
    end
  end

  def unarchive
    session[:return_to] = request.referer
    @archived = true
    if change_room_archived_mode(room: @room, archived: false)
      redirect_back_or_default(notice: "The room was unarchived")
    else
      @rooms = Room.archived
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])

      authorize @room
    end

    def delete_room(room)
      ActiveRecord::Base.transaction do
        begin
          Resource.where(room_id: room.id).delete_all
          SpecificAttribute.where(room_id: room.id).delete_all
          Note.where(room_id: room.id).delete_all
          floor = room.floor
          room.delete
          floor.delete unless floor.rooms.present?
        rescue StandardError 
          raise ActiveRecord::Rollback
          false
        end
        true
      end
    end

    def change_room_archived_mode(room:, archived:)
      ActiveRecord::Base.transaction do
        raise ActiveRecord::Rollback unless room.update(archived: archived)
        raise ActiveRecord::Rollback unless room.specific_attributes.update(archived: archived)
        raise ActiveRecord::Rollback unless room.resources.update(archived: archived)
      end
      true
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:rmrecnbr, :room_number, :room_type, :floor_id, :archived)
    end
end

app/views/rooms/_attributes_list.html.erb
<table class="table text-center ms-3">
  <thead>
  <tr>
    <th scope="col" class="text-start">Description</th>
    <th scope="col">Include Yes/No Buttons</th>
    <th scope="col">Include Quantity Box </th>
  </tr>
  </thead>
  <tbody>
  <% attributes.each do |attribute| %>
    <tr>
      <td class="text-start"><%= attribute.description %></td>
      <td>
        <% if attribute.need_checkbox %>
          <i class="bi bi-check-circle-fill text-primary"></i>
        <% end %>
      </td>
      <td>
        <% if attribute.need_quantity_box %>
          <i class="bi bi-check-circle-fill text-primary"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/rooms/_form.html.erb
<%= turbo_frame_tag 'new_room' do %>  
  <%= form_with model: @room do |form| %>
    <% if room.errors.any? %>
      <div class="text-danger">
        <h2><%= pluralize(room.errors.count, "error") %></h2>

        <ul>
          <% room.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :rmrecnbr, 'Room Record Number (Barcode) *', class: "nowrap" %>
      <%= form.text_field :rmrecnbr, required: true, placeholder: "Room Record Number" %>
    </div>

    <%= hidden_field_tag 'building_id', @building.id %>

    <div class="d-flex flex-row justify-content-start align-items-center gap-3">
      <%= form.submit "Create Room", class: "btn btn-primary", data: { turbo_frame: "_top" } %>
      <%= link_to 'Cancel', building_path(@building), class: "link_to", data: { turbo_frame: "_top" } %>
    </div>
  <% end %>
<% end %>

app/views/rooms/_resources_list.html.erb
<table class="table ms-3">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Type</th>
  </tr>
  </thead>
  <tbody>
  <% resources.each do |resource| %>
    <tr>
      <td><%= resource.name %></td>
      <td><%= resource.resource_type %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>" class="ms-3">
  <div class="fs-5 fw-bold text-success">
    <%= RoomStatus.new(room).show_status %>
  </div>
  <div class="py-1 d-flex flex-row align-items-center gap-3">
    <div class="fs-5 fw-bold">Room Record Number (Barcode): </div>
    <div class="fs-5"><%= room.rmrecnbr %></div>
  </div>

  <div class="py-1 d-flex flex-row align-items-center gap-3">
    <div class="fs-5 fw-bold">Building:</div>
    <div class="fs-5"><%= room.floor.building.name %></div>
  </div>

  <div class="py-1 d-flex flex-row align-items-center gap-3">
    <div class="fs-5 fw-bold">Floor:</div>
    <div class="fs-5"><%= room.floor.name %></div>
  </div>

  <div class="py-1 d-flex flex-row align-items-center gap-3">
    <div class="fs-5 fw-bold">Room Number: </div>
    <div class="fs-5"><%= room.room_number %></div>
  </div>

  <div class="py-1 d-flex flex-row align-items-center gap-3">
    <div class="fs-5 fw-bold">Room Type:</div>
    <div class="fs-5"><%= room.room_type %></div>
  </div>

  <div class="py-1 d-flex flex-row align-items-center gap-3">
    <% unless room.room_states.present? %>
      <%= link_to room_path(room), class: "link_to", data: { turbo_confirm: "Are you sure you want to delete this room?" , turbo_method: :delete } do %>
        Delete Room <i class="bi bi-trash-fill text-danger"></i>
      <% end %>
    <% else %>
      <% if room.archived %>
        <%= link_to unarchive_room_path(room), class: "link_to", data: { turbo_confirm: "Are you sure you want to unarchive this room?" , turbo_method: :post }  do %>
          Unarchive Room <i class="bi bi-archive text-success"></i>
        <% end %>
      <% else %>
        <%= link_to archive_room_path(room), class: "link_to", data: { turbo_confirm: "Are you sure you want to archive this room?" , turbo_method: :post }  do %>
          Archive Room <i class="bi bi-archive-fill text-success"></i>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/_specific_attributes_list.html.erb
<table class="table text-center mt-3">
  <thead>
  <tr>
    <th scope="col" class="text-start">Description</th>
    <th scope="col">Needs Checkbox?</th>
    <th scope="col">Needs Quantity Box?</th>
  </tr>
  </thead>
  <tbody>
  <% specific_attributes.each do |specific_attribute| %>
    <tr>
      <td class="text-start"><%= specific_attribute.description %></td>
      <td>
        <% if specific_attribute.need_checkbox %>
          <i class="bi bi-check-circle-fill text-primary"></i>
        <% end %>
      </td>
      <td>
        <% if specific_attribute.need_quantity_box %>
          <i class="bi bi-check-circle-fill text-primary"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h1>New Room</h1>
<h2><%= @building.name %></h2>

<%= render "form", room: @room %>

app/views/rooms/show.html.erb
<div class="container-fluid">

  <div class="d-flex flex-row justify-content-between align-items-center mb-3">
    <h1>Room: <%= @room.full_name  %></h1>
    <div class="d-flex align-items-end flex-column gap-1">
      <%= link_to 'Back to Building', building_path(@room.floor.building), class: "link_to" %>
      <%= link_to 'Show Room Checks', room_room_states_path(@room), class: 'btn btn-primary h-50 mt-auto mb-auto' %>
    </div>
  </div>

  <%= render @room %>

  <div class="w-75">
    <div class="d-flex flex-row align-items-center gap-4">
      <h2>Common Attributes</h2>
      <%= link_to common_attributes_path, class: 'text-primary link-underline-primary link-underline-opacity-0 link-underline-opacity-100-hover' do %>
        Edit Common Attributes <i class="bi bi-pencil-square text-primary"></i>
      <% end %>
    </div>
    <%= render 'attributes_list', attributes: @common_attributes %>
  </div>

  <div class="w-75">
    <div class="d-flex flex-row align-items-center gap-4">
      <h2>Specific Attributes</h2>
      <%= link_to room_specific_attributes_path(@room), class: 'text-primary link-underline-primary link-underline-opacity-0 link-underline-opacity-100-hover' do %>
        Edit Specific Attributes <i class="bi bi-pencil-square text-primary"></i>
      <% end %>
    </div>
    <%= render 'attributes_list', attributes: @room.active_specific_attributes %>
  </div>

  <div class="w-75">
    <div class="d-flex flex-row align-items-center justify-content-between">
      <h2>Resources</h2>
    </div>
    <%= render 'resources_list', resources: @room.active_resources %>
  </div>

  <% if is_admin? %>
    <div class="w-75">
      <h2>Notes:</h2>
      <%= turbo_frame_tag "new_note" do %>
        <%= render "notes/form", note: @new_note %>
      <% end %>
      <div class="notes" id="notes">
        <%= render @notes %>
      </div>
    </div>
  <% end %>
</div>