config/routes.rb
Rails.application.routes.draw do

  resources :app_preferences, except: [:show] do
    collection do
      get 'configure_prefs'
      post 'save_configured_prefs'
    end
  end
  resources :announcements, only: [ :index, :show, :edit, :update ]

  resources :resource_states, except: [:index, :show, :destroy]
  post '/resource_states/update_resource_states/:id', to: 'resource_states#update_resource_states', as: :update_resource_states
  
  resources :specific_attribute_states, except: [:index, :show, :destroy]
  post '/specific_attribute_states/update_specific_attribute_states/:id', to: 'specific_attribute_states#update_specific_attribute_states', as: :update_specific_attribute_states

  resources :common_attribute_states, except: [:index, :show, :destroy]
  post '/common_attribute_states/update_common_attribute_states/:id', to: 'common_attribute_states#update_common_attribute_states', as: :update_common_attribute_states

  resources :common_attributes, except: [:show]
  post 'unarchive_common_attribute/:id', to: 'common_attributes#unarchive', as: :unarchive_common_attribute
  resources :rovers, except: [:show]
  
  resources :zones, :except => [:show]
  resources :zones do
    resources :buildings, module: :zones
  end
  delete 'zones/buildings/:zone_id/:id', to: 'zones/buildings#remove_building', as: :remove_building

  resources :reports, only: [:index] do
    collection do
      get 'number_of_room_issues_report', to: 'reports#number_of_room_issues_report'
      get 'room_issues_report', to: 'reports#room_issues_report'
      get 'inspection_rate_report', to: 'reports#inspection_rate_report'
      get 'no_access_report', to: 'reports#no_access_report'
      get 'common_attribute_states_report', to: 'reports#common_attribute_states_report'
      get 'specific_attribute_states_report', to: 'reports#specific_attribute_states_report'
      get 'resource_states_report', to: 'reports#resource_states_report'
      get 'no_access_for_n_times_report', to: 'reports#no_access_for_n_times_report'
      get 'not_checked_rooms_report', to: 'reports#not_checked_rooms_report'
    end
  end

  get 'dashboard', to: 'static_pages#dashboard', as: :dashboard

  resources :rooms, :except => [:index, :edit, :update]
  resources :rooms do
    resources :specific_attributes, module: :rooms, except: [:show]
    resources :room_states, module: :rooms, except: [:destroy]
    resources :room_tickets, module: :rooms, only: [:send_email_for_tdx_ticket]
  end
  post 'archive_room/:id', to: 'rooms#archive', as: :archive_room
  post 'unarchive_room/:id', to: 'rooms#unarchive', as: :unarchive_room
  resources :notes, :except => [:index]
  post 'archive_specific_attribute/:room_id/:id', to: 'rooms/specific_attributes#archive', as: :archive_specific_attribute
  post 'unarchive_specific_attribute/:room_id/:id', to: 'rooms/specific_attributes#unarchive', as: :unarchive_specific_attribute

  resources :floors
  resources :buildings do
    resources :floors do 
      resources :rooms, module: :floors
    end
  end
  post 'archive_building/:id', to: 'buildings#archive', as: :archive_building
  post 'unarchive_building/:id', to: 'buildings#unarchive', as: :unarchive_building
  post 'unarchive_building_index/:id/:show_archived', to: 'buildings#unarchive_index', as: :unarchive_building_index

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions"} do
    delete 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resource :rover_navigation, only: [] do
    member do
      get 'zones'
      get 'buildings'
      get 'rooms'
      get 'confirmation'
    end
  end

  get 'redirect_to_unchecked_form/:id', to: 'rover_navigations#redirect_to_unchecked_form', as: :redirect_to_unchecked_form


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'static_pages#about', as: :all_root

  get 'static_pages/about'

  get 'welcome_rovers', to: 'static_pages#welcome_rovers', as: :welcome_rovers

  post '/send_email_for_tdx_ticket/:room_id', to: 'rooms/room_tickets#send_email_for_tdx_ticket', as: :send_email_for_tdx_ticket

  # LSA TDX Feedback routes
  mount LsaTdxFeedback::Engine => '/lsa_tdx_feedback', as: 'lsa_tdx_feedback'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?

  # Place this at the very end of the file to catch all undefined routes
  # get '*path', to: 'application#render_404', via: :all

end

app/controllers/rover_navigations_controller.rb
class RoverNavigationsController < ApplicationController
  before_action :auth_user

  def zones
    authorize :rover_navigation, :zones?
    @zones = Zone.all.order(:name)
  end

  def buildings
    authorize :rover_navigation, :buildings?

    @zone = Zone.find(params[:zone_id])
    @buildings = @zone.buildings.order(:name)

    if params[:search].present?
      @buildings = @buildings.where("name ILIKE :search OR address ILIKE :search", search: "%#{params[:search]}%")
    end
  end

  def rooms
    authorize :rover_navigation, :rooms?
    @floor = Floor.find(params[:floor_id])
    @rooms = @floor.active_rooms.order(:room_number)

    if params[:search].present?
      @rooms = @rooms.where("room_number ILIKE :search", search: "%#{params[:search]}%")
    end
  end

  def redirect_to_unchecked_form
    room = Room.find(params[:id])
    authorize :rover_navigation
    room_state = RoomStatus.new(room).room_state_today
    if room_state.common_attribute_states.any?
      if room_state.specific_attribute_states.any?
        if room_state.resource_states.any?
        else
          redirect_to redirect_rover_to_correct_state(room: room, room_state: room_state, step: "specific_attributes", mode: "new") 
        end 
      else 
        redirect_to redirect_rover_to_correct_state(room: room, room_state: room_state, step: "common_attributes", mode: "new")
      end
    else
      redirect_to redirect_rover_to_correct_state(room: room, room_state: room_state, step: "room", mode: "new")
    end
  end

  def confirmation
    authorize :rover_navigation, :confirmation?
    @room = Room.find(params[:room_id])
 
    if @room.nil?
      redirect_to zones_rover_navigation_path, notice: 'Room does not exist!'
    end

    @room_state_today = RoomStatus.new(@room).room_state_today

    if @room_state_today.nil?
      redirect_to zones_rover_navigation_path, notice: 'Room not checked or Invalid!'
    end
    r = Recommendation.new(@room)
    @building_floors = r.all_floors
    @next_room = r.next_room
    @previous_room = r.previous_room
  end
end

app/views/rover_navigations/_form_progress_bar.html.erb
<div class="progress mb-3 w-50" role="progressbar" style="height: 20px;"
     aria-label="Rover form progress"
     aria-valuenow="<%= show_room_percentage(room) %>>"
     aria-valuemin="0" aria-valuemax="100">
  <div class="progress-bar bg-success" style="width: <%= show_room_percentage(room) %>%">
    <%= show_room_percentage(room) %>%
  </div>
</div>

app/views/rover_navigations/buildings.html.erb
<div class="container-fluid mt-3">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "Zones", zones_rover_navigation_path, class: 'link_to' %></li>
      <li class="breadcrumb-item active" aria-current="page">Buildings</li>
    </ol>
  </nav>

  <h1>Buildings for <%= @zone.name %></h1>

  <%= form_with url: buildings_rover_navigation_path, method: :get, local: true do |form| %>
    <%= form.hidden_field :zone_id, value: @zone.id %>
    <%= form.text_field :search, value: params[:search], placeholder: "Enter name or address", aria: { label: "search" } %>
    <%= form.submit "Search" %>
    <%= link_to 'Clear Filter', buildings_rover_navigation_path(zone_id: @zone.id), class: 'link_to' %>
  <% end %>

  <% @buildings.each_with_index do |building, i| %>
    <div class="card mt-3">
      <div class="card-header">
        <p>
          <%= building.name %>
          <i id="redirect-to-maps" data-controller="redirect" data-action="click->redirect#onMapClick" role="button" class="bi bi-geo-alt text-success cursor-pointer" aria-label="open building on maps" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Open Google Maps" data-url="<%= google_map_navigation_path(building.full_address) %>"></i>
        </p>
        <p class="text-success">
          <%= show_building_status(building) %>
        </p>
        </div>
      <div class="card-body">
        <p class="card-text">
          <%= building.full_address %>
        </p>
        <div class="dropdown border-0">
          <button class="btn btn-primary dropdown-toggle" type="button" id="floorDropdownButton<%= i %>" data-bs-toggle="dropdown" aria-expanded="false">
            Select Floor
          </button>
          <ul class="dropdown-menu" aria-labelledby="floorDropdownButton<%= i %>">
            <% sort_floors(building.floors).each do |floor| %>
              <% if floor.active_rooms.any? %>
                <li><%= link_to "Floor #{floor.name}", rooms_rover_navigation_path(floor_id: floor.id), class: "dropdown-item btn-primary" %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/rover_navigations/confirmation.html.erb
<style>

  @media (min-width: 1025px) {
    .h-custom {
      height: 100vh !important;
    }
  }

  .horizontal-timeline .items {
    border-top: 3px solid;
  }
  
  .horizontal-timeline .items .items-list {
    position: relative;
    margin-right: 0;
    padding-top: 15px;
  }

  .horizontal-timeline .items .items-list p {
    font-size: 14px;
  }

  @media (max-width: 380px) {
    .horizontal-timeline .items .items-list p {
      font-size: 12px;
    }
  }

  .horizontal-timeline .items .items-list:before {
    content: "";
    position: absolute;
    height: 8px;
    width: 8px;
    border-radius: 50%;
    background-color: var(--bs-primary);
    top: 0;
    margin-top: -5px;
  }
</style>
<section>
  <h1 class="text-center">Check Confirmation</h1>
  <div class="container py-3 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-8 col-xl-6">
        <div class="card border-top border-bottom border-3 border-primary">
          <div class="card-body p-2">
            <p class="lead fw-bold mb-2 text-primary">Room Information</p>
            <div class="row">
              <div class="col">
                <p class="small text-muted mb-1">Date</p>
                <p><%= @room_state_today.updated_at.strftime('%m/%d/%Y') %></p>
              </div>
              <div class="col">
                <p class="small text-muted mb-1">Building</p>
                <p><%= @room.floor.building.name %></p>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <p class="small text-muted mb-1">Floor</p>
                <p><%= @room.floor.name %></p>
              </div>
              <div class="col">
                <p class="small text-muted mb-1">Room No.</p>
                <p><%= @room.room_number %></p>
              </div>
            </div>
            <hr />
            <p class="lead fw-bold pb-2 text-primary">Room Check Progress</p>
            <div class="row">
              <div class="col-lg-12">
                <div class="horizontal-timeline">
                  <div class="progress-bar bg-primary"></div>
                  <ul class="list-inline items border-primary d-flex justify-content-between">
                    <li class="list-inline-item items-list">
                      <p class="py-1 px-2 rounded text-white bg-primary">Common</p>
                    </li>
                    <li class="list-inline-item items-list">
                      <p class="py-1 px-2 rounded text-white bg-primary">Specific</p>
                    </li>
                    <li class="list-inline-item items-list">
                      <p class="py-1 px-2 rounded text-white bg-primary">Resources</p>
                    </li>
                    <li class="list-inline-item items-list text-end" style="margin-right: 8px;">
                      <p style="margin-right: -8px;" class="py-1 px-2 rounded text-white bg-success">Done!</p>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <hr />
            <% if @next_room && @previous_room %>
              <p class="lead fw-bold text-primary">Start Checking Another Room</p>
              <div class="d-flex justify-content-between gap-2 mt-3 text-nowrap">
                <% unless @previous_room == @next_room %>
                  <%= link_to new_room_room_state_path(room_id: @previous_room.id), class: "btn btn-success" do %>
                    <i class="bi bi-arrow-left"></i>
                    <span>
                      <%= "#{@previous_room.room_number}, Floor #{@previous_room.floor.name}" %>
                    </span>
                  <% end %>
                <% end %>
                <%= link_to new_room_room_state_path(room_id: @next_room.id), class: "btn btn-success" do %>
                  <span>
                    <%= "#{@next_room.room_number}, Floor #{@next_room.floor.name}" %>
                    <i class="bi bi-arrow-right"></i>
                  </span>
                <% end %>
              </div>

              <div class="dropdown border-0 mt-3 mb-3">
                <button class="btn btn-primary dropdown-toggle" type="button" id="floorDropdownButton" data-bs-toggle="dropdown" aria-expanded="false">
                  Select Floor
                </button>
                <ul class="dropdown-menu" aria-labelledby="floorDropdownButton">
                  <% @building_floors.each do |floor| %>
                    <% if floor.floor_has_unchecked_rooms? %>
                      <li><%= link_to "Floor #{floor.name}", rooms_rover_navigation_path(floor_id: floor.id), class: "dropdown-item btn-primary" %></li>
                    <% end %>
                  <% end %>
                </ul>
              </div>
              <%= link_to "Back to Buildings", buildings_rover_navigation_path(zone_id: @room.floor.building.zone.id), class: "btn btn-primary"%>
            <% else %>
              <p class="lead fw-bold mb-5 text-success">All Rooms in Building are checked!</p>
              <%= link_to "Back to Buildings", buildings_rover_navigation_path(zone_id: @room.floor.building.zone.id), class: "btn btn-primary"%>
            <% end %>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/rover_navigations/rooms.html.erb
<div class="container-fluid mt-3">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "Zones", zones_rover_navigation_path, class: 'link_to' %></li>
      <li class="breadcrumb-item"><%= link_to "Buildings", buildings_rover_navigation_path(zone_id: @floor.building.zone.id), class: 'link_to' %></li>
      <li class="breadcrumb-item active" aria-current="page">Rooms</li>
    </ol>
  </nav>

  <h1>
    Rooms for <%= @floor.building.name %> (Floor <%= @floor.name %>)
    <i id="redirect-to-maps" data-controller="redirect" data-action="click->redirect#onMapClick" role="button" class="bi bi-geo-alt text-success cursor-pointer" aria-label="open building on maps" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Open Google Maps" data-url="<%= google_map_navigation_path(@floor.building.full_address) %>"></i>
  </h1>

  <%= form_with url: rooms_rover_navigation_path, method: :get, local: true do |form| %>
    <%= form.hidden_field :floor_id, value: @floor.id %>
    <%= form.text_field :search, value: params[:search], placeholder: "Enter a room number", aria: { label: "search" } %>
    <%= form.submit "Search" %>
    <%= link_to 'Clear Filter', rooms_rover_navigation_path(floor_id: @floor.id), class: 'link_to' %>
  <% end %>

  <% @rooms.each do |room| %>
    <div class="card mt-3">
      <div class="card-header">
        <p>
          Room: <%= room.room_number %>
        </p>
        <p class="text-success">
          <%= RoomStatus.new(room).show_status %>
        </p>
      </div>
      <div class="card-body">
        <p class="card-text">
          Room Type: <%= room.room_type %>
        </p>
        <p class="text-danger">Last Time Checked: <%= show_date_with_time(room.last_time_checked) %> </p>
        <% if RoomStatus.new(room).room_checked_today? %>
          <% if RoomStatus.new(room).calculate_percentage.to_f < 100.00 %>
            <%= link_to "Continue Checking #{room.room_number}", redirect_to_unchecked_form_path(room), class: "btn btn-primary" %>
          <% else %>
            <%= link_to "Edit Today's #{room.room_number}", edit_room_room_state_path(room, RoomStatus.new(room).room_state_today.id), class: "btn btn-primary" %>
          <% end %>
        <% else %>
          <%= link_to "Start Checking #{room.room_number}", new_room_room_state_path(room), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/rover_navigations/zones.html.erb
<div class="container-fluid mt-3">
  <h1>Zones Available</h1>

  <% @zones.each do |zone| %>
    <div class="card mt-3">
      <div class="card-header">
        <p>
          <%= zone.name %>
        </p>
      </div>
      <div class="card-body">
        <p class="card-text">
          <%= truncate(
                zone.buildings.order(:name).pluck(:name).join(', '),
                length: 60, omission: '...') %>
        </p>
        <%= link_to "#{zone.name} Details", buildings_rover_navigation_path(zone_id: zone.id), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>